# Generated by Django 4.1 on 2022-09-09 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=100, null=True),
        ),
    ]
