# Generated by Django 4.1 on 2022-10-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
